Pin estimator version since dev2019062000 is broken.
tf-nightly-2.0-preview does not pin a release of estimator and the release at
head is broken. Sonnet does not import or use estimator, however when using
tf.function autograph forces the estimator module to be loaded (as part of
`_fix_linecache_record`) which triggers an issue with loading:

ModuleNotFoundError: No module named 'tensorflow_core.estimator'
PiperOrigin-RevId: 254155508
Change-Id: I42f92d702eb32c406acc7a849b59916172becc87